apiVersion: v1
kind: Pod
metadata:
  name: vuln-scan
spec:
  containers:
  - name: vuln-scan-py
    image: 709004257235.dkr.ecr.us-east-1.amazonaws.com/vuln-scan-py:latest
    env:
      - name: AWS_ACCESS_KEY_ID
        value: "xxx"
      - name: AWS_SECRET_ACCESS_KEY
        value: "xxx"
